config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :goals, except: :show
  get 'my_goals' => 'goals#show', as: :goals_show 
  post '/goals/:id/done' => 'goals#mark_as_done', as: :mark_goal
  root 'goals#index'

end

app/models/goal.rb
class Goal < ActiveRecord::Base

	has_attached_file :image, styles: { medium: "300x300#", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:edit, :update, :destroy, :mark_as_done]

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all.sample(6)
  end

  # GET /my_goals
  def show
    @goals = Goal.where(user: current_user)
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)
    @goal.user = current_user

    respond_to do |format|
      if @goal.save
        format.html { redirect_to goals_show_path, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to goals_show_path, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def mark_as_done
    @goal.is_passed = true
    respond_to do |format|
      if @goal.save
        format.html { redirect_to goals_show_path, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:text,:is_passed,:image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= form_for(@goal) do |f| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= f.label :text, "Цель", class: "col-xs-2 col-form-label" %>
    <div class="col-xs-10">
      <%= f.text_field :text, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :is_passed, "Выполнена", class: "col-xs-2 col-form-label"  %>
    <div class="col-xs-10">
      <%= f.check_box :is_passed, class: "checkbox" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :image, "Картинка", class: "col-xs-2 col-form-label"  %>
    <div class="col-xs-10">
      <%= f.file_field :image, class: "form-control-file" %>
      </div>
  </div>
  <div class="btn btn-active">
    <%= f.submit   "Отправить" %>
  </div>
<% end %>

app/views/goals/edit.html.erb
<div class="container">
<h1>Редактировать цель</h1>

<%= render 'form' %>

</div>

app/views/goals/index.html.erb
    <!-- Image Background Page Header -->
    <!-- Note: The background image is set within the business-casual.css file. -->
    <header class="business-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="tagline">Если цель не твоя, жизнь проходит мимо</h1>
                </div>
            </div>
        </div>
    </header>

    <!-- Page Content -->
    <div class="container">

        <hr>

        <div class="row">
            <div class="col-sm-12">
                <h2>Что я здесь делаю?</h2>
                <p>Постановке целей в наше время уделяют очень много времени, и не зря. Если ты не знаешь в какую сторону двигаться, то в любом случае придешь не туда.</p>
                <p>Сядьте и потратьте пару часов времени на постановку целей на жизнь. Будьте изобретательны и рисковы. Помечайте выполненные цели и делитесь своим прогрессом с друзьями!</p>
                <p>Цель помечается серым, если она не выполнена и приобретает краски после выполнения. Давайте делать нашу жизнь красочней!</p>
                <p>
                <% if user_signed_in? %>
                      <%=link_to 'Начать использование &raquo;'.html_safe, goals_show_path , :class =>  "btn btn-default btn-lg" %>
                    <%else%>
                      <%=link_to 'Начать использование &raquo;'.html_safe, new_user_session_url, :class => "btn btn-default btn-lg"%>
                        <%end%>
                
                                </p>
            </div>
            
        </div>
        <!-- /.row -->

        <hr>

        <div class="row">
            <h1>Цели других людей</h1>
            <%@goals.each_with_index do |goal,index|%>
            <%='<div class="row">'.html_safe if index%3==0%>
            <div class="col-sm-4">
                <%if !goal.image.url.ends_with?("missing.png")%>
                <%=image_tag goal.image(:medium), class: "img-circle img-responsive img-center"%>
                <%else%>
                <img class="img-circle img-responsive img-center" src="http://placehold.it/300x300" alt="">
            <%end%>
                <h2><%=goal.text%></h2>
            </div>
            <%='</div>'.html_safe  if index%3==2%>
            <%end%>
            
        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Jimmy 2016</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>

app/views/goals/new.html.erb
<div class="container">
<h1>Добавить цель</h1>
<%= render 'form' %>
</div>

app/views/goals/show.html.erb
<div class="container">
 <hr>
<div class="row">
<%if @goals.empty? %>
 <h2> Вы не добавили еще ни одной цели</h2>
<%end%>
            <%@goals.each_with_index do |goal,index|%>
            <%='<div class="row">'.html_safe if index%3==0%>
            <div class="col-sm-4">
            <%if !goal.image.url.ends_with?("missing.png")%>
            	<%=image_tag goal.image(:medium), class: "img-circle img-responsive img-center" + (' grayscale' unless goal.is_passed).to_s %>
            <%else%>
            	<img class="img-circle img-responsive img-center" src="http://placehold.it/300x300" alt="">
            <%end%>
                <h2><%=goal.text%></h2>
                <%=link_to 'Редактировать', edit_goal_path(goal), html_options = {class: "btn btn-primary"} %>
                <%if !goal.is_passed%>
                <%=link_to 'Выполнить', mark_goal_path(goal), :method => :post, class: "btn btn-success" %>
                <%end%>
            </div>
            <%='</div>'.html_safe  if index%3==2%>
            <%end%>
            
</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                 
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <%=link_to 'Главная', goals_path%>
                    </li>
                    <% if user_signed_in? %>
                    <li>
                      <%=link_to 'Мои цели', goals_show_path%>
                    </li>
                    <li>
                      <%=link_to 'Добавить цель', new_goal_path%>
                    </li>
                    <%end%>
                    <li>
                    <% if user_signed_in? %>
                      <%=link_to 'Выйти',  destroy_user_session_path, :method => :delete%>
                    <%else%>
                      <%=link_to 'Войти\Зарегистрироваться', new_user_session_url%>
                        <%end%>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Goals</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header"%>
<%= yield %>

</body>
</html>